#! /usr/bin/python3
# -*- coding:utf-8 -*-


draw_module_ = '提取模块名称'
draw_requirement_ = '提取特性名称'
generate_serial_ = '生成编号'
serial_number_ = '编号'
requirement_naming_ = '需求命名'
module_naming_ = '模块命名'
project_name_ = '项目名'
code_name_ = '项目代码'
former_prefix_ = '原前缀'
operator_ = '运营商'
revision_ = '版本号'
priority_ = '优先级'
feature_property_ = '特性属性'
feature_state_ = '特性状态'
feature_source_ = '特性来源'
feature_prerequisite_ = '约束限制'
feature_owner_ = '负责人'
jira_story_ = '关联故事'
ui_wireframe_ = '关联UI'
delivered_version_ = '交付版本'
delivered_state_ = '交付状态'
module_name_ = '模块名'
abbreviation_ = '缩写'
tag_ = '模块标签'
tags_ = '标签组成'
tag_serial_ = '标签序列'
assignee_ = '指派给'
multi_assignee_ = '多个指派'
reportee_ = '汇报给'
page_url_ = '链接'
requirement_name_ = '标题'
requirement_source_ = '需求来源'
requirement_content_ = '内容'
page_outline_ = '页面标题'
to_space_ = '到空间中'
locate_at_ = '位于此'

to_do_ = '待处理'

